

server:
  port: 65530
  
spring:
  application:
    name: Streams
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver 
    url: mysql:jdbc://localhost:3306/streamdb?createDatabaseIfNotExist=true
    username: ${Name}
    password: ${Pwd}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
