

server:
  port: 65530
  
spring:
  application:
    name: Streams
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver 
    url: jdbc:mysql://localhost:3306/sbdb?createDatabaseIfNotExist=true
    username: ${Name}
    password: ${Pwd}
  data:
    jpa:
      repositories:
        enabled: true
     
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
